"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { ArrowLeft, Globe, FileText, Loader2, Save } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Separator } from "@/components/ui/separator";
import { RichTextEditor } from "@/components/ui/rich-text-editor";
import {
  Popover,
  PopoverContent,
  PopoverTrigger
} from "@/components/ui/popover";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";

import { useCreateArticle } from "../api/use-create-article";
import { useUpdateArticle } from "../api/use-update-article";
import { NewsArticle } from "core/zod";

const formSchema = z.object({
  title: z.string().min(1, "Title is required"),
  slug: z.string().optional().nullable(),
  excerpt: z.string().optional().nullable(),
  content: z.string().min(1, "Content is required"),
  featuredImage: z.string().optional().nullable(),
  isPublished: z.boolean(),
  metaTitle: z.string().optional().nullable(),
  metaDescription: z.string().optional().nullable(),
  keywords: z.string().optional().nullable(),
});

type FormValues = z.infer<typeof formSchema>;

interface ArticleEditorProps {
  article?: NewsArticle;
}

export default function ArticleEditor({ article }: ArticleEditorProps) {
  const router = useRouter();
  const isEditing = !!article;
  const { mutate: createArticle, isPending: isCreating } = useCreateArticle();
  const { mutate: updateArticle, isPending: isUpdating } = useUpdateArticle();
  const isPending = isCreating || isUpdating;
  const [settingsOpen, setSettingsOpen] = useState(false);

  const form = useForm<FormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      title: article?.title || "",
      excerpt: article?.excerpt || "",
      content: article?.content || "",
      featuredImage: article?.featuredImage || "",
      isPublished: article?.isPublished || false,
      slug: article?.slug || "",
      metaTitle: article?.metaTitle || "",
      metaDescription: article?.metaDescription || "",
      keywords: article?.keywords || "",
    }
  });

  const titleRef = useRef<HTMLTextAreaElement | null>(null);
  const { ref: titleInputRef, ...titleRegisterProps } = form.register("title");

  // Auto-resize title textarea
  useEffect(() => {
    const el = titleRef.current;
    if (el) {
      el.style.height = "auto";
      el.style.height = el.scrollHeight + "px";
    }
  }, [form.watch("title")]);

  const handleSave = (isPublished?: boolean) => {
    form.setValue("isPublished", isPublished !== undefined ? isPublished : form.getValues("isPublished"));
    form.handleSubmit((values) => {
      const payload = { ...values, isPublished: isPublished !== undefined ? isPublished : values.isPublished };
      // Remove empty string to allow null or autogenerated slug
      if (payload.slug === "") payload.slug = null;
      if (isEditing) {
        updateArticle(
          { id: article.id, data: payload },
          { onSuccess: () => router.push("/admin/article-management") }
        );
      } else {
        createArticle(payload as any, {
          onSuccess: () => router.push("/admin/article-management")
        });
      }
    })();
  };

  const isPublished = form.watch("isPublished");
  const featuredImage = form.watch("featuredImage");

  return (
    <div className="min-h-screen bg-white flex flex-col">
      {/* Sticky top bar */}
      <header className="sticky top-0 z-50 border-b bg-white/95 backdrop-blur">
        <div className="max-w-5xl mx-auto px-4 h-14 flex items-center justify-between gap-4">
          <button
            onClick={() => router.push("/admin/article-management")}
            className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Articles
          </button>

          <div className="flex items-center gap-2">
            {/* Settings popover */}
            <Popover open={settingsOpen} onOpenChange={setSettingsOpen}>
              <PopoverTrigger asChild>
                <Button variant="outline" size="sm" className="gap-1.5">
                  <FileText className="h-3.5 w-3.5" />
                  Article Settings
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-80 space-y-4" align="end">
                <div className="space-y-1.5">
                  <Label>Excerpt</Label>
                  <Textarea
                    placeholder="Short summary shown in listings..."
                    rows={3}
                    {...form.register("excerpt")}
                  />
                </div>
                <div className="space-y-1.5">
                  <Label>Cover Image URL</Label>
                  <Input
                    placeholder="https://example.com/image.jpg"
                    {...form.register("featuredImage")}
                  />
                  {featuredImage && (
                    <img
                      src={featuredImage}
                      alt="Cover"
                      className="mt-2 h-28 w-full object-cover rounded-md border"
                    />
                  )}
                </div>
                <Separator />
                <div className="space-y-1.5">
                  <Label>URL Slug</Label>
                  <Input
                    placeholder="Auto-generated if empty"
                    {...form.register("slug")}
                  />
                </div>
                <div className="space-y-1.5">
                  <Label>SEO Title</Label>
                  <Input
                    placeholder="Meta title..."
                    {...form.register("metaTitle")}
                  />
                </div>
                <div className="space-y-1.5">
                  <Label>SEO Description</Label>
                  <Textarea
                    placeholder="Meta description for search engines..."
                    rows={2}
                    {...form.register("metaDescription")}
                  />
                </div>
                <div className="space-y-1.5">
                  <Label>Keywords</Label>
                  <Input
                    placeholder="Comma separated keywords..."
                    {...form.register("keywords")}
                  />
                </div>
                <Separator />
                <div className="flex items-center justify-between rounded-md border p-3">
                  <div>
                    <p className="text-sm font-medium">Published</p>
                    <p className="text-xs text-muted-foreground">Publicly visible</p>
                  </div>
                  <Switch
                    checked={isPublished}
                    onCheckedChange={(val) => form.setValue("isPublished", val)}
                  />
                </div>
              </PopoverContent>
            </Popover>

            <Button
              variant="outline"
              size="sm"
              onClick={() => handleSave(false)}
              disabled={isPending}
              className="gap-1.5"
            >
              <Save className="h-3.5 w-3.5" />
              Save Draft
            </Button>

            <Button
              size="sm"
              onClick={() => handleSave(true)}
              disabled={isPending}
              className="gap-1.5"
            >
              {isPending ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
              ) : (
                <Globe className="h-3.5 w-3.5" />
              )}
              {isEditing && isPublished ? "Update" : "Publish"}
            </Button>
          </div>
        </div>
      </header>

      {/* Editor body */}
      <main className="flex-1 overflow-y-auto bg-white">
        <div className="max-w-[740px] mx-auto w-full px-6 py-16 md:py-24">
          {/* Cover image preview at top */}
          {featuredImage && (
            <div className="mb-10 group relative">
              <img
                src={featuredImage}
                alt="Cover"
                className="w-full h-[350px] object-cover rounded-lg border shadow-sm transition-all group-hover:shadow-md"
              />
            </div>
          )}

          {/* Title */}
          <textarea
            ref={(e) => {
              titleInputRef(e);
              titleRef.current = e;
            }}
            placeholder="Title"
            className="w-full resize-none border-0 bg-transparent text-5xl font-bold tracking-tight text-zinc-900 placeholder:text-zinc-300 focus:outline-none leading-[1.15] mb-8 overflow-hidden font-serif"
            rows={1}
            {...titleRegisterProps}
          />

          {/* Rich text content */}
          <div className="prose prose-zinc prose-lg max-w-none">
            <RichTextEditor
              value={form.watch("content")}
              onChange={(val) => form.setValue("content", val)}
              placeholder="Tell your story..."
              className="text-xl leading-relaxed font-serif"
            />
          </div>

          {/* Inline errors */}
          <div className="mt-8 pt-8 border-t space-y-2">
            {form.formState.errors.title && (
              <p className="text-sm font-medium text-destructive">
                Title: {form.formState.errors.title.message}
              </p>
            )}
            {form.formState.errors.content && (
              <p className="text-sm font-medium text-destructive">
                Content: {form.formState.errors.content.message}
              </p>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}
