import { z } from "zod";
export declare const ad: z.ZodObject<{
    id: z.ZodString;
    hotelId: z.ZodNullable<z.ZodString>;
    roomId: z.ZodNullable<z.ZodString>;
    restaurantId: z.ZodNullable<z.ZodString>;
    organizationId: z.ZodString;
    userId: z.ZodString;
    title: z.ZodString;
    description: z.ZodNullable<z.ZodString>;
    imageUrl: z.ZodNullable<z.ZodString>;
    redirectUrl: z.ZodNullable<z.ZodString>;
    startDate: z.ZodNullable<z.ZodCoercedString<unknown>>;
    endDate: z.ZodNullable<z.ZodCoercedString<unknown>>;
    isActive: z.ZodBoolean;
    priority: z.ZodEnum<{
        normal: "normal";
        high: "high";
        low: "low";
    }>;
    placement: z.ZodNullable<z.ZodString>;
    promoCode: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    discountPercent: z.ZodOptional<z.ZodNullable<z.ZodCoercedNumber<unknown>>>;
    isUniquePerUser: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    usageLimit: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    usageCount: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    minBookingValue: z.ZodOptional<z.ZodDefault<z.ZodCoercedNumber<unknown>>>;
    createdAt: z.ZodCoercedString<unknown>;
    updatedAt: z.ZodNullable<z.ZodCoercedString<unknown>>;
}, z.core.$strip>;
export declare const adInsertSchema: z.ZodObject<{
    description: z.ZodNullable<z.ZodString>;
    hotelId: z.ZodNullable<z.ZodString>;
    imageUrl: z.ZodNullable<z.ZodString>;
    restaurantId: z.ZodNullable<z.ZodString>;
    isActive: z.ZodBoolean;
    startDate: z.ZodNullable<z.ZodCoercedString<unknown>>;
    endDate: z.ZodNullable<z.ZodCoercedString<unknown>>;
    promoCode: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    title: z.ZodString;
    roomId: z.ZodNullable<z.ZodString>;
    redirectUrl: z.ZodNullable<z.ZodString>;
    priority: z.ZodEnum<{
        normal: "normal";
        high: "high";
        low: "low";
    }>;
    placement: z.ZodNullable<z.ZodString>;
    discountPercent: z.ZodOptional<z.ZodNullable<z.ZodCoercedNumber<unknown>>>;
    isUniquePerUser: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    usageLimit: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    usageCount: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    minBookingValue: z.ZodOptional<z.ZodDefault<z.ZodCoercedNumber<unknown>>>;
}, z.core.$strip>;
export declare const adUpdateSchema: z.ZodObject<{
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    hotelId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    imageUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    restaurantId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    isActive: z.ZodOptional<z.ZodBoolean>;
    startDate: z.ZodOptional<z.ZodNullable<z.ZodCoercedString<unknown>>>;
    endDate: z.ZodOptional<z.ZodNullable<z.ZodCoercedString<unknown>>>;
    promoCode: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    title: z.ZodOptional<z.ZodString>;
    roomId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    redirectUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    priority: z.ZodOptional<z.ZodEnum<{
        normal: "normal";
        high: "high";
        low: "low";
    }>>;
    placement: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    discountPercent: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodCoercedNumber<unknown>>>>;
    isUniquePerUser: z.ZodOptional<z.ZodOptional<z.ZodDefault<z.ZodBoolean>>>;
    usageLimit: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    usageCount: z.ZodOptional<z.ZodOptional<z.ZodDefault<z.ZodNumber>>>;
    minBookingValue: z.ZodOptional<z.ZodOptional<z.ZodDefault<z.ZodCoercedNumber<unknown>>>>;
}, z.core.$strip>;
export type adUpdateType = z.infer<typeof adUpdateSchema>;
export type ad = z.infer<typeof ad>;
export type adInsertType = z.infer<typeof adInsertSchema>;
