import { z } from "zod";
export declare const restaurantImageSchema: z.ZodObject<{
    id: z.ZodString;
    restaurantId: z.ZodString;
    imageUrl: z.ZodString;
    altText: z.ZodNullable<z.ZodString>;
    displayOrder: z.ZodNullable<z.ZodNumber>;
    isThumbnail: z.ZodNullable<z.ZodBoolean>;
    createdAt: z.ZodCoercedString<unknown>;
    updatedAt: z.ZodNullable<z.ZodCoercedString<unknown>>;
}, z.core.$strip>;
export type RestaurantImage = z.infer<typeof restaurantImageSchema>;
export declare const restaurantSchema: z.ZodObject<{
    id: z.ZodString;
    hotelId: z.ZodString;
    createdBy: z.ZodString;
    organizationId: z.ZodString;
    name: z.ZodString;
    description: z.ZodNullable<z.ZodString>;
    brandName: z.ZodNullable<z.ZodString>;
    buffetMetadata: z.ZodNullable<z.ZodString>;
    street: z.ZodString;
    city: z.ZodString;
    state: z.ZodString;
    country: z.ZodString;
    postalCode: z.ZodString;
    latitude: z.ZodNullable<z.ZodCoercedString<unknown>>;
    longitude: z.ZodNullable<z.ZodCoercedString<unknown>>;
    phone: z.ZodNullable<z.ZodString>;
    email: z.ZodNullable<z.ZodString>;
    website: z.ZodNullable<z.ZodString>;
    starRating: z.ZodNullable<z.ZodCoercedString<unknown>>;
    checkInTime: z.ZodNullable<z.ZodString>;
    checkOutTime: z.ZodNullable<z.ZodString>;
    cuisineType: z.ZodNullable<z.ZodString>;
    dressCode: z.ZodNullable<z.ZodString>;
    totalSeats: z.ZodNullable<z.ZodNumber>;
    allocatedSeats: z.ZodNullable<z.ZodNumber>;
    breakfastPrice: z.ZodNullable<z.ZodCoercedString<unknown>>;
    lunchPrice: z.ZodNullable<z.ZodCoercedString<unknown>>;
    dinnerPrice: z.ZodNullable<z.ZodCoercedString<unknown>>;
    buffetPrice: z.ZodNullable<z.ZodCoercedString<unknown>>;
    pricePerSeat: z.ZodNullable<z.ZodCoercedString<unknown>>;
    customPrices: z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodObject<{
        label: z.ZodString;
        price: z.ZodCoercedNumber<unknown>;
    }, z.core.$strip>>>>;
    menuUrl: z.ZodNullable<z.ZodString>;
    status: z.ZodEnum<{
        pending_approval: "pending_approval";
        active: "active";
        inactive: "inactive";
        under_maintenance: "under_maintenance";
    }>;
    createdAt: z.ZodCoercedString<unknown>;
    updatedAt: z.ZodNullable<z.ZodCoercedString<unknown>>;
}, z.core.$strip>;
export type Restaurant = z.infer<typeof restaurantSchema>;
export declare const restaurantInsertSchema: z.ZodObject<{
    name: z.ZodString;
    email: z.ZodNullable<z.ZodString>;
    status: z.ZodEnum<{
        pending_approval: "pending_approval";
        active: "active";
        inactive: "inactive";
        under_maintenance: "under_maintenance";
    }>;
    description: z.ZodNullable<z.ZodString>;
    brandName: z.ZodNullable<z.ZodString>;
    street: z.ZodString;
    city: z.ZodString;
    state: z.ZodString;
    country: z.ZodString;
    postalCode: z.ZodString;
    latitude: z.ZodNullable<z.ZodCoercedString<unknown>>;
    longitude: z.ZodNullable<z.ZodCoercedString<unknown>>;
    phone: z.ZodNullable<z.ZodString>;
    website: z.ZodNullable<z.ZodString>;
    starRating: z.ZodNullable<z.ZodCoercedString<unknown>>;
    checkInTime: z.ZodNullable<z.ZodString>;
    checkOutTime: z.ZodNullable<z.ZodString>;
    hotelId: z.ZodString;
    buffetMetadata: z.ZodNullable<z.ZodString>;
    totalSeats: z.ZodNullable<z.ZodNumber>;
    allocatedSeats: z.ZodNullable<z.ZodNumber>;
    breakfastPrice: z.ZodNullable<z.ZodCoercedString<unknown>>;
    lunchPrice: z.ZodNullable<z.ZodCoercedString<unknown>>;
    dinnerPrice: z.ZodNullable<z.ZodCoercedString<unknown>>;
    buffetPrice: z.ZodNullable<z.ZodCoercedString<unknown>>;
    pricePerSeat: z.ZodNullable<z.ZodCoercedString<unknown>>;
    customPrices: z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodObject<{
        label: z.ZodString;
        price: z.ZodCoercedNumber<unknown>;
    }, z.core.$strip>>>>;
    cuisineType: z.ZodNullable<z.ZodString>;
    dressCode: z.ZodNullable<z.ZodString>;
    menuUrl: z.ZodNullable<z.ZodString>;
}, z.core.$strip>;
export type RestaurantInsert = z.infer<typeof restaurantInsertSchema>;
export declare const restaurantUpdateSchema: z.ZodObject<{
    name: z.ZodOptional<z.ZodString>;
    email: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    status: z.ZodOptional<z.ZodEnum<{
        pending_approval: "pending_approval";
        active: "active";
        inactive: "inactive";
        under_maintenance: "under_maintenance";
    }>>;
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    brandName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    street: z.ZodOptional<z.ZodString>;
    city: z.ZodOptional<z.ZodString>;
    state: z.ZodOptional<z.ZodString>;
    country: z.ZodOptional<z.ZodString>;
    postalCode: z.ZodOptional<z.ZodString>;
    latitude: z.ZodOptional<z.ZodNullable<z.ZodCoercedString<unknown>>>;
    longitude: z.ZodOptional<z.ZodNullable<z.ZodCoercedString<unknown>>>;
    phone: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    website: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    starRating: z.ZodOptional<z.ZodNullable<z.ZodCoercedString<unknown>>>;
    checkInTime: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    checkOutTime: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    hotelId: z.ZodOptional<z.ZodString>;
    buffetMetadata: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    totalSeats: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    allocatedSeats: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    breakfastPrice: z.ZodOptional<z.ZodNullable<z.ZodCoercedString<unknown>>>;
    lunchPrice: z.ZodOptional<z.ZodNullable<z.ZodCoercedString<unknown>>>;
    dinnerPrice: z.ZodOptional<z.ZodNullable<z.ZodCoercedString<unknown>>>;
    buffetPrice: z.ZodOptional<z.ZodNullable<z.ZodCoercedString<unknown>>>;
    pricePerSeat: z.ZodOptional<z.ZodNullable<z.ZodCoercedString<unknown>>>;
    customPrices: z.ZodOptional<z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodObject<{
        label: z.ZodString;
        price: z.ZodCoercedNumber<unknown>;
    }, z.core.$strip>>>>>;
    cuisineType: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    dressCode: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    menuUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, z.core.$strip>;
export type RestaurantUpdate = z.infer<typeof restaurantUpdateSchema>;
export declare const restaurantWithRelationsSchema: z.ZodObject<{
    id: z.ZodString;
    hotelId: z.ZodString;
    createdBy: z.ZodString;
    organizationId: z.ZodString;
    name: z.ZodString;
    description: z.ZodNullable<z.ZodString>;
    brandName: z.ZodNullable<z.ZodString>;
    buffetMetadata: z.ZodNullable<z.ZodString>;
    street: z.ZodString;
    city: z.ZodString;
    state: z.ZodString;
    country: z.ZodString;
    postalCode: z.ZodString;
    latitude: z.ZodNullable<z.ZodCoercedString<unknown>>;
    longitude: z.ZodNullable<z.ZodCoercedString<unknown>>;
    phone: z.ZodNullable<z.ZodString>;
    email: z.ZodNullable<z.ZodString>;
    website: z.ZodNullable<z.ZodString>;
    starRating: z.ZodNullable<z.ZodCoercedString<unknown>>;
    checkInTime: z.ZodNullable<z.ZodString>;
    checkOutTime: z.ZodNullable<z.ZodString>;
    cuisineType: z.ZodNullable<z.ZodString>;
    dressCode: z.ZodNullable<z.ZodString>;
    totalSeats: z.ZodNullable<z.ZodNumber>;
    allocatedSeats: z.ZodNullable<z.ZodNumber>;
    breakfastPrice: z.ZodNullable<z.ZodCoercedString<unknown>>;
    lunchPrice: z.ZodNullable<z.ZodCoercedString<unknown>>;
    dinnerPrice: z.ZodNullable<z.ZodCoercedString<unknown>>;
    buffetPrice: z.ZodNullable<z.ZodCoercedString<unknown>>;
    pricePerSeat: z.ZodNullable<z.ZodCoercedString<unknown>>;
    customPrices: z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodObject<{
        label: z.ZodString;
        price: z.ZodCoercedNumber<unknown>;
    }, z.core.$strip>>>>;
    menuUrl: z.ZodNullable<z.ZodString>;
    status: z.ZodEnum<{
        pending_approval: "pending_approval";
        active: "active";
        inactive: "inactive";
        under_maintenance: "under_maintenance";
    }>;
    createdAt: z.ZodCoercedString<unknown>;
    updatedAt: z.ZodNullable<z.ZodCoercedString<unknown>>;
    images: z.ZodOptional<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        restaurantId: z.ZodString;
        imageUrl: z.ZodString;
        altText: z.ZodNullable<z.ZodString>;
        displayOrder: z.ZodNullable<z.ZodNumber>;
        isThumbnail: z.ZodNullable<z.ZodBoolean>;
        createdAt: z.ZodCoercedString<unknown>;
        updatedAt: z.ZodNullable<z.ZodCoercedString<unknown>>;
    }, z.core.$strip>>>;
}, z.core.$strip>;
export type RestaurantWithRelations = z.infer<typeof restaurantWithRelationsSchema>;
export declare const restaurantTypeQueryParamsSchema: z.ZodObject<{
    page: z.ZodOptional<z.ZodString>;
    limit: z.ZodOptional<z.ZodString>;
    sort: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
        asc: "asc";
        desc: "desc";
    }>>>;
    search: z.ZodOptional<z.ZodString>;
    hotelId: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const restaurantQueryParamsSchema: z.ZodObject<{
    page: z.ZodOptional<z.ZodString>;
    limit: z.ZodOptional<z.ZodString>;
    sort: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
        asc: "asc";
        desc: "desc";
    }>>>;
    search: z.ZodOptional<z.ZodString>;
    hotelId: z.ZodOptional<z.ZodString>;
    status: z.ZodOptional<z.ZodEnum<{
        pending_approval: "pending_approval";
        active: "active";
        inactive: "inactive";
        under_maintenance: "under_maintenance";
    }>>;
    floorNumber: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const restaurantBookingSchema: z.ZodObject<{
    id: z.ZodString;
    restaurantId: z.ZodString;
    userId: z.ZodString;
    numberOfChairs: z.ZodNumber;
    bookingDate: z.ZodCoercedDate<unknown>;
    totalDeposit: z.ZodCoercedString<unknown>;
    status: z.ZodEnum<{
        pending: "pending";
        arrived: "arrived";
        no_show: "no_show";
        refunded: "refunded";
    }>;
    checkInAt: z.ZodNullable<z.ZodCoercedDate<unknown>>;
    refundId: z.ZodNullable<z.ZodString>;
    paymentId: z.ZodNullable<z.ZodString>;
    createdAt: z.ZodCoercedString<unknown>;
    updatedAt: z.ZodNullable<z.ZodCoercedString<unknown>>;
}, z.core.$strip>;
export type RestaurantBooking = z.infer<typeof restaurantBookingSchema>;
export declare const restaurantBookingInsertSchema: z.ZodObject<{
    status: z.ZodEnum<{
        pending: "pending";
        arrived: "arrived";
        no_show: "no_show";
        refunded: "refunded";
    }>;
    restaurantId: z.ZodString;
    numberOfChairs: z.ZodNumber;
    bookingDate: z.ZodCoercedDate<unknown>;
    totalDeposit: z.ZodCoercedString<unknown>;
    checkInAt: z.ZodNullable<z.ZodCoercedDate<unknown>>;
    refundId: z.ZodNullable<z.ZodString>;
    paymentId: z.ZodNullable<z.ZodString>;
}, z.core.$strip>;
export type RestaurantBookingInsert = z.infer<typeof restaurantBookingInsertSchema>;
