import { z } from "zod";
export declare const siteSettingsSchema: z.ZodObject<{
    id: z.ZodNumber;
    siteName: z.ZodString;
    siteLogo: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    siteMetaDescription: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    seoKeywordsShort: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    seoKeywordsLong: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    contactEmail: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    contactPhone: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    contactAddress: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    copyrightText: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    privacyPolicy: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    termsAndConditions: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    bookingPolicy: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    refundPolicy: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    defaultCommissionRate: z.ZodUnion<[z.ZodString, z.ZodNumber]>;
    isOnlinePaymentEnabled: z.ZodOptional<z.ZodBoolean>;
    createdAt: z.ZodUnion<[z.ZodDate, z.ZodString]>;
    updatedAt: z.ZodNullable<z.ZodUnion<[z.ZodDate, z.ZodString]>>;
}, z.core.$strip>;
export declare const insertSiteSettingsSchema: z.ZodObject<{
    siteName: z.ZodString;
    siteLogo: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    siteMetaDescription: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    seoKeywordsShort: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    seoKeywordsLong: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    contactEmail: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    contactPhone: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    contactAddress: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    copyrightText: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    privacyPolicy: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    termsAndConditions: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    bookingPolicy: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    refundPolicy: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    defaultCommissionRate: z.ZodUnion<[z.ZodString, z.ZodNumber]>;
    isOnlinePaymentEnabled: z.ZodOptional<z.ZodBoolean>;
}, z.core.$strip>;
export declare const updateSiteSettingsSchema: z.ZodObject<{
    siteName: z.ZodOptional<z.ZodString>;
    siteLogo: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    siteMetaDescription: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    seoKeywordsShort: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    seoKeywordsLong: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    contactEmail: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    contactPhone: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    contactAddress: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    copyrightText: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    privacyPolicy: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    termsAndConditions: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bookingPolicy: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    refundPolicy: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    defaultCommissionRate: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodNumber]>>;
    isOnlinePaymentEnabled: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
}, z.core.$strip>;
export type SiteSettings = z.infer<typeof siteSettingsSchema>;
export type InsertSiteSettings = z.infer<typeof insertSiteSettingsSchema>;
export type UpdateSiteSettings = z.infer<typeof updateSiteSettingsSchema>;
